/**
 * scrape-mfm: extract Black Templars points (+ roles) from the Munitorum Field
 * Manual site's React Flight (RSC) payload.
 *
 * The MFM is a Next.js App Router app; the page data is server-rendered into a
 * flight payload returned when the route is requested with an `RSC: 1` header.
 * Point values are lazy refs ($L<id>) resolved by sibling flight rows
 * (`<id>:["$","span",null,{"children":"80 pts"}]`).
 *
 * Output: scripts/points-overrides.json (consumed by compile-data), keyed by
 * the slug of the datasheet name. Run `node scripts/scrape-mfm.mjs` then
 * `npm run compile-data`. Pass --dump to print the parse without writing.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'

const URL = 'https://mfm.warhammer-community.com/en/black-templars'
const CACHE = 'data-sources/mfm/black-templars.rsc.txt'
const OUT = 'scripts/points-overrides.json'

const slug = (s) =>
  s.toLowerCase().replace(/[’']/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

async function getPayload() {
  if (process.argv.includes('--cached') && existsSync(CACHE)) {
    return readFileSync(CACHE, 'utf8')
  }
  const res = await fetch(URL, { headers: { RSC: '1' } })
  if (!res.ok) throw new Error(`MFM fetch ${res.status}`)
  const text = await res.text()
  if (!existsSync('data-sources/mfm')) mkdirSync('data-sources/mfm', { recursive: true })
  writeFileSync(CACHE, text)
  return text
}

function parse(text) {
  // 1) ref id -> resolved text (e.g. "80 pts")
  const refMap = {}
  for (const line of text.split('\n')) {
    const m = line.match(/^([0-9a-f]+):(.*)$/i)
    if (!m) continue
    const c = m[2].match(/"children":"([^"]+)"/)
    if (c) refMap[m[1]] = c[1]
  }
  const resolvePts = (id) => {
    const v = refMap[id]
    const n = v && v.match(/(\d+)\s*pts/)
    return n ? Number(n[1]) : null
  }

  // 2) walk name spans. Cost-label spans ("YOUR UNIT COSTS" etc.) and the
  // LEADER/SUPPORT headers sit between a unit's name and its cost lines, so we
  // must NOT treat them as names — only real names bound a unit's window.
  const isLabel = (n) =>
    /^YOUR\b/.test(n) || n === 'LEADER' || n === 'SUPPORT' ||
    /^(UNITS|DETACHMENTS|ENHANCEMENTS|SPACE MARINES)$/.test(n)

  const nameRe = /"children":"([^"]+)"\}\]/g
  const names = []
  for (let m; (m = nameRe.exec(text)); ) if (!isLabel(m[1])) names.push({ name: m[1], idx: m.index })

  // Sum every integer in the model text: "1 model"->1, "5 models"->5,
  // "1 Sword Brother, 4 Neophytes, 5 Initiates"->10.
  const sumModels = (t) => (t.match(/\d+/g) ?? []).reduce((a, n) => a + Number(n), 0) || 1

  const units = []
  for (let i = 0; i < names.length; i++) {
    const win = text.slice(names[i].idx, names[i + 1]?.idx ?? text.length)
    const costRe = /\[false,"([^"]+)"\]\}\],"\$L([0-9a-f]+)"/g
    const sizeOptions = []
    for (let cm; (cm = costRe.exec(win)); ) {
      const pts = resolvePts(cm[2])
      if (pts == null) continue
      sizeOptions.push({ modelsText: cm[1], models: sumModels(cm[1]), points: pts })
    }
    if (sizeOptions.length) units.push({ name: names[i].name, sizeOptions })
  }
  return { units, refCount: Object.keys(refMap).length }
}

const text = await getPayload()
const { units, refCount } = parse(text)
console.log(`payload chars: ${text.length}, refs: ${refCount}, units parsed: ${units.length}`)

if (process.argv.includes('--dump')) {
  for (const u of units.slice(0, 60)) {
    console.log(`${u.name}: ${u.sizeOptions.map((s) => `${s.modelsText}=${s.points}`).join(' | ')}`)
  }
  process.exit(0)
}

// Build overrides keyed by slug; preserve any roles already in the file.
const prev = existsSync(OUT) ? JSON.parse(readFileSync(OUT, 'utf8')) : {}
const out = {
  _comment:
    'AUTO-GENERATED by scripts/scrape-mfm.mjs from the Munitorum Field Manual RSC payload. Keyed by datasheet-name slug. Re-run after MFM updates, then npm run compile-data. "role" is preserved from prior manual edits.',
}
for (const u of units) {
  const id = slug(u.name)
  const sizeOptions = u.sizeOptions.map((s) => ({ models: s.models ?? 1, points: s.points }))
  out[id] = { ...(prev[id]?.role ? { role: prev[id].role } : {}), sizeOptions }
}
writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n')
console.log(`✓ wrote ${Object.keys(out).length - 1} unit overrides -> ${OUT}`)
